# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Spojit Documentation
site_url: https://docs.spojit.com/
site_author: Spojit
site_description: >-

# Header Links
header_links:
  display: true
  contact:
    url: https://www.spojit.com/contact
    title: Contact Us
  pricing:
    url: https://www.spojit.com/pricing
    title: Pricing
  signup:
    url: https://app.spojit.com/register/
    title: Free Trial

# Copyright
copyright: Copyright &copy; 2021 Spojit

# Configuration
theme:
  name: material
  custom_dir: spojit
  logo: assets/logo.svg

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: deep orange
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico

# Plugins
plugins:
  - search
  - mermaid2
  # - minify:
  #     minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.spojit.com
    - icon: fontawesome/solid/id-card
      link: https://app.spojit.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCmrHMMPQCE7EaQR3_vPqXKw
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/spojit/

# Extra CSS stylesheet
extra_css:
  - stylesheets/extra.css
    
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Introduction: index.md
  - User Guide:
    - My Account:
      - Account:
        - Change password: user-guide/my-account/account/change-password.md
        - Reset password: user-guide/my-account/account/reset-password.md
        - Delete account: user-guide/my-account/account/delete-account.md
      - Billing:
        - Change billing: user-guide/my-account/billing/change-billing.md
        - View invoices: user-guide/my-account/billing/view-invoices.md
      - Subscription:
        - Create subscription: user-guide/my-account/subscription/create-subscription.md
        - Change subscription: user-guide/my-account/subscription/change-subscription.md
        - Cancel subscription: user-guide/my-account/subscription/cancel-subscription.md
    - Integration:
      - Create integration: user-guide/integration/create-integration.md
      - Edit integration:
        - Basic info: user-guide/integration/edit/basic-info.md
        - Configuration: user-guide/integration/edit/configuration.md
        - Schedule: user-guide/integration/edit/schedule.md
        - Webhook: user-guide/integration/edit/webhook.md
        - Logs: user-guide/integration/edit/logs.md
      - Run now: user-guide/integration/run-now.md
      - Delete integration: user-guide/integration/delete-integration.md
    - Workflow:
      - Introduction: user-guide/workflow/introduction.md
      - Create workflow: user-guide/workflow/create-workflow.md
      - Add service: user-guide/workflow/add-service.md
      - Connect services: user-guide/workflow/connect-services.md
      - Run workflow: user-guide/workflow/run-workflow.md
    - Mapper:
      - Functions:
        - Array Functions: user-guide/mapper/functions/array.md
        - Datetime Functions: user-guide/mapper/functions/datetime.md
        - Formula Functions: user-guide/mapper/functions/formula.md
        - Math Functions: user-guide/mapper/functions/math.md
        - String Functions: user-guide/mapper/functions/string.md
    - Services:
      - CSV Parser: user-guide/services/csv-parser.md
      - Dataset Service: user-guide/services/dataset.md
      - Deputy: user-guide/services/deputy-service.md
      - Document OCR: user-guide/services/document-ocr.md
      - Filter: user-guide/services/filter.md
      - FTP Service: user-guide/services/ftp-service.md
      - Iterator: user-guide/services/iterator.md
      - JSON Parser: user-guide/services/json-parser.md
      - Mailer: user-guide/services/mailer.md
      - Magento 2: user-guide/services/magento2-service.md
      - Mapper Service: user-guide/services/mapper-service.md
      - Netsuite REST Service: user-guide/services/netsuite-rest-service.md
      - Netsuite SOAP Service: user-guide/services/netsuite-soap-service.md
      - Parallel Gateway: user-guide/services/parallel-gateway.md
      - REST Service: user-guide/services/rest-service.md
      - Revel Systems: user-guide/services/revel-service.md
      - SFTP Service: user-guide/services/sftp-service.md
      - ShipStation: user-guide/services/shipstation-service.md
      - SmartFreight Service: user-guide/services/smartfreight-service.md
      - Start Service: user-guide/services/start-service.md
      - Unleashed Software: user-guide/services/unleashed-service.md
      - WooCommerce: user-guide/services/woocommerce-service.md
      - XLSX Service: user-guide/services/xlsx-service.md
  - Connectors Guide:
    - WooCommerce:
      - WooCommerce Authorization: connectors/woocommerce/woocommerce-authorization.md
      - WooCommerce Legacy API: connectors/woocommerce/woocommerce-legacy-api.md
      - WooCommerce Webhooks: connectors/woocommerce/woocommerce-webhooks.md
    - Unleashed Software:
      - Unleashed Authorization: connectors/unleashed/unleashed-authorization.md
      - Unleashed Warehouse Code: connectors/unleashed/unleashed-warehouse-code.md
  - Library: library/index.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
