# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Spojit Documentation
site_url: https://docs.spojit.com/
site_author: Spojit Pty Ltd
site_description: >-
  Intelligent business process management platform

## Repository
#repo_name: squidfunk/mkdocs-material
#repo_url: https://github.com/squidfunk/mkdocs-material

# Copyright
copyright: Copyright &copy; 2025 Spojit Pty Ltd

# Configuration
theme:
  name: material
  custom_dir: spojit

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: spojit
      primary: spojit
      accent: spojit
#      toggle:
#        icon: material/toggle-switch
#        name: Switch to dark mode
#    - scheme: slate
#      primary: indigo
#      accent: indigo
#      toggle:
#        icon: material/toggle-switch-off-outline
#        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: logo
  logo: assets/logo.svg

# Plugins
plugins:
  - search
  - mkdocs-video
  - minify:
      minify_html: true

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/globe
      link: https://www.spojit.com
    - icon: fontawesome/solid/id-card
      link: https://app.spojit.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCmrHMMPQCE7EaQR3_vPqXKw
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/spojit/

# Extra CSS stylesheet
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting started:
      - Overview: getting-started/index.md
      - Create a workflow: getting-started/workflows/create-workflow.md
      - Add a service: getting-started/workflows/add-service.md
      - Connect services: getting-started/workflows/connect-services.md
      - Run workflow: getting-started/workflows/run-workflow.md
      - Workflow configuration:
        - Basic info: getting-started/workflows/configuration/basic-info.md
        - Schedule: getting-started/workflows/configuration/schedule.md
        - Webhook: getting-started/workflows/configuration/webhook.md
        - Logs: getting-started/workflows/configuration/logs.md

  - Account setup:
      - My account:
          - Change password: setup/account/change-password.md
          - Reset password: setup/account/reset-password.md
          - Enable 2FA: setup/account/enable-2fa.md
          - Delete account: setup/account/delete-account.md
      - Billing:
          - Change billing: setup/billing/change-billing.md
          - View invoices: setup/billing/view-invoices.md
      - Subscription:
          - Create subscription: setup/subscription/create-subscription.md
          - Change subscription: setup/subscription/change-subscription.md
          - Cancel subscription: setup/subscription/cancel-subscription.md
  - AI Development:
      - Getting started:
          - Quickstart: ai-development/index.md
      - Providers:
          - Anthropic: ai-development/providers/anthropic.md
          - DeepSeek: ai-development/providers/deepseek.md
          - Groq: ai-development/providers/groq.md
          - MistralAI: ai-development/providers/mistralai.md
          - OpenAI: ai-development/providers/openai.md
          - VertexAI: ai-development/providers/vertexai.md
      - Services:
          - Simple Chat: ai-development/services/simple-chat.md
          - Agents: ai-development/services/agents.md
  - Reference:
      - reference/index.md
      - Mapping functions:
          - reference/mapping/index.md
          - Array Functions: reference/mapping/functions/array.md
          - Datetime Functions: reference/mapping/functions/datetime.md
          - Formula Functions: reference/mapping/functions/formula.md
          - Math Functions: reference/mapping/functions/math.md
          - String Functions: reference/mapping/functions/string.md
      - Services:
          - reference/services/index.md
          - Array Service: reference/services/array-service.md
          - CSV Parser: reference/services/csv-parser.md
          - Dataset Service: reference/services/dataset.md
          - DEAR Systems: reference/services/dear-systems-service.md
          - Delay Service: reference/services/delay-service.md
          - Deputy: reference/services/deputy-service.md
          - Document OCR: reference/services/document-ocr.md
          - FTP Service: reference/services/ftp-service.md
          - JSON Parser: reference/services/json-parser.md
          - Mailer: reference/services/mailer.md
          - Magento 2: reference/services/magento2-service.md
          - Mapper Service: reference/services/mapper-service.md
          - Netsuite REST Service: reference/services/netsuite-rest-service.md
          - Netsuite RESTlet Service: reference/services/netsuite-restlet-service.md
          - Netsuite SOAP Service: reference/services/netsuite-soap-service.md
          - REST Service: reference/services/rest-service.md
          - Revel Systems: reference/services/revel-service.md
          - SFTP Service: reference/services/sftp-service.md
          - Shipping Tools: reference/services/shipping-tools.md
          - ShipStation: reference/services/shipstation-service.md
          - SmartFreight Service: reference/services/smartfreight-service.md
          - SMTP Mailer Service: reference/services/smtp-mailer.md
          - Start Service: reference/services/start-service.md
          - Unleashed Software: reference/services/unleashed-service.md
          - WooCommerce: reference/services/woocommerce-service.md
          - XLSX Service: reference/services/xlsx-service.md
      - Flow controls:
          - reference/flow-controls/index.md
          - Filter: reference/flow-controls/filter.md
          - Iterator: reference/flow-controls/iterator.md
          - Parallel Gateway: reference/flow-controls/parallel-gateway.md
      - Popular integrations:
          - reference/integrations/index.md
          - WooCommerce:
              - WooCommerce Authorization: reference/integrations/woocommerce/woocommerce-authorization.md
              - WooCommerce Legacy API: reference/integrations/woocommerce/woocommerce-legacy-api.md
              - WooCommerce Webhooks: reference/integrations/woocommerce/woocommerce-webhooks.md
          - Unleashed Software:
              - Unleashed Authorization: reference/integrations/unleashed/unleashed-authorization.md
              - Unleashed Warehouse Code: reference/integrations/unleashed/unleashed-warehouse-code.md
  - Contact: https://www.spojit.com/contact" target="_blank
  - Register: https://app.spojit.com/register" target="_blank
  - Log in: https://app.spojit.com/login" target="_blank